### ISSUE TITLE
关于非 iOS 设备的 dpr 疑惑

### ISSUE THREAD

**Issue by zenozeng** [amfe/lib-flexible#11]
想问一下为什么针对所有的非 iPhone 设备都用了 dpr = 1 的方案呢？
有些疑惑，有的 Android 设备的 devicePixelRatio 其实不也是会有不少非 1 的情况吗？

```javascript
    if (!dpr && !scale) {
        var isAndroid = win.navigator.appVersion.match(/android/gi);
        var isIPhone = win.navigator.appVersion.match(/iphone/gi);
        var devicePixelRatio = win.devicePixelRatio;
        if (isIPhone) {
            // iOS下，对于2和3的屏，用2倍的方案，其余的用1倍方案
            if (devicePixelRatio >= 3 && (!dpr || dpr >= 3)) {                
                dpr = 3;
            } else if (devicePixelRatio >= 2 && (!dpr || dpr >= 2)){
                dpr = 2;
            } else {
                dpr = 1;
            }
        } else {
            // 其他设备下，仍旧使用1倍的方案
            dpr = 1;
        }
        scale = 1 / dpr;
    }
```

**Comment by q165411054** [comment]
估计我们也可以优化非 iPhone 设备的dpr设置逻辑

**Comment by lidianhao123** [comment]
isIPhone变量在Apple ipad设备下为null，dpr=1；无法正常使用。请问为什么如此设计？

**Comment by baiwenbao** [comment]
部分Android设备 px不会随viewport进行缩放

**Comment by xch89820** [comment]
Android 使用dpr=1，并且init-scale=1，需要配合width=device-width，使其保持物理宽度，保证字体大小。

**Comment by Aaaaaashu** [comment]
@airen 不知道大漠能不能讲解下这个问题呢？
我也是有这样的困惑。

**Comment by leozdgao** [comment]
+1

**Comment by yuchuanxi** [comment]
@lidianhao123 估计人家是手机／平板／pc在服务端返回页面的时候已经做了区分的。
所以，此处只考虑mobile

**Comment by codekissyoung** [comment]
@yuchuanxi 然而并没有，在Ipad上依然是手机淘宝，540px定宽居中，两边留白！！！

**Comment by codekissyoung** [comment]
@xch89820 width=device-width 是为了兼容 windows iPhone

**Comment by dd1994** [comment]
我看 readme 里说字体大小设置用这样的方式：
```less
div {
    width: 1rem; 
    height: 0.4rem;
    font-size: 12px; // 默认写上dpr为1的fontSize
}

[data-dpr="2"] div {
    font-size: 24px;
}

[data-dpr="3"] div {
    font-size: 36px;
}
```


那那些安卓机的字体是不是都会出问题
