### ISSUE TITLE
不定宽图片在高 DPR 场景下的适配问题

### ISSUE THREAD

**Issue by jin5354** [amfe/lib-flexible#127]
例如有一个图片预览组件，点击小图展示全屏大图，展示大图时使用 css 控制宽度：

```scss
.img-wrapper {
  display: flex;
  align-items: center;
  justify-content: center;
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;

  img {
    max-width: 100vw;
  }
}
```

意图是 img 宽度不足屏幕宽度时，按照原本尺寸展示；如果超过屏幕宽度，则按 100% 屏幕宽度展示。

在高 DPR 场景下，例如 6p 或者 1080p 分辨率的安卓手机，经过 initial-scale 变换之后 CSS 像素与物理像素同样高，此时分辨率较低的图片显示非常小。此时需要手动实现这种不定宽的图片在不同 DPR 下的宽度适配，也就是在 DPR=1 的情况下图片 width = 原尺寸；DPR=2 情况下 width = 2倍原尺寸。

目前是这样手动实现适配的：

```scss
[data-dpr="1"] .img-wrapper img {
  max-width: 100vw;
  max-height: 100vh;
}
[data-dpr="2"] .img-wrapper img {
  max-width: 50vw;
  max-height: 50vh;
  transform: scale(2,2)
}
[data-dpr="3"] .img-wrapperimg {
  max-width: 33.33vw;
  max-height: 33.33vh;
  transform: scale(3,3)
}
```

不知有没有更恰当的实现方式。每个地方都手动调整还是不太优雅。
