### ISSUE TITLE
'hairlines'是什么?

### ISSUE THREAD

**Issue by qingmingsang** [amfe/lib-flexible#169]
```
    if (testElement.offsetHeight === 1) {
      docEl.classList.add('hairlines')
    }
```

**Comment by haozhaohang** [comment]
就是一个检测而且，看浏览器是否支持1像素

**Comment by qingmingsang** [comment]
@haozhaohang   额，我知道是检测1px，我只是想知道这个样式是什么

**Comment by kkkisme** [comment]
``` css
.hairlines .thin-border {
    border-width: 0.5px !important
}
```
@qingmingsang
