### ISSUE TITLE
关于字体做适配的问题

### ISSUE THREAD

**Issue by Tomatoo** [amfe/lib-flexible#44]
关于字体如何做屏幕适配，我有三个问题：

- 设计那边给了一个640的稿子(5S)，如果标注字体是20px，那么在5S这种dpr为2的屏幕上，我应该设置字体为20是吧，然后6P这种dpr为3的稿子上，按照比例应该是30px是吧，然后一般的安卓机设置字体为10px是吧，但是由于webkit内核最小字体12的限制，最后渲染出来是12px对吧？
- 贵公司的设计那边在640的稿子上给出的最小字体是多少呢，因为我发现20px的字体在5S上这种高清屏幕上太小了，不知道你们是如何处理的。
- 之前看过大漠的一篇文章，讲了使用saas的混合宏来定义字体比较方便：
`@mixin font-dpr($font-size){
    font-size: $font-size;

    [data-dpr="2"] & {
        font-size: $font-size * 2;
    }

    [data-dpr="3"] & {
        font-size: $font-size * 3;
    }
}`

但是在less上如何写出这种混合宏呢，我还没有思路。

谢谢。

**Comment by riskers** [comment]
@Tomatoo  less不是一样的么：

```css
.font-dpr(@font-size){
    font-size: @font-size;

    [data-dpr="2"] & {
        font-size: @font-size * 2;
    }

    [data-dpr="3"] & {
        font-size: @font-size * 3;
    }
}
```
