### ISSUE TITLE
关于border 1px的问题？

### ISSUE THREAD

**Issue by flyer153** [amfe/lib-flexible#60]
目前在项目中用的时候发现1px的问题lib-flexible里并没解决，有什么好的解决方案吗？

**Comment by hanai** [comment]
``` scss
.box {
  &:before {
    position: absolute;
    left: 0;
    top: 0;
    width: 1px;
    background: #e5e5e5;
    height: 100%;
    transform: scaleX(.5);
  }
}
```
